services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-${DOCKER_PROJECT_NAME:-default}
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HOST_FRONTEND_PORT}:80
    env_file:
      - ./.env
    networks:
      - default-network
    depends_on:
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
    command: >
      sh -c "ln -sf /dev/stdout /var/log/nginx/access.log &&
             ln -sf /dev/stderr /var/log/nginx/error.log &&
             nginx -g 'daemon off;'"

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend-${DOCKER_PROJECT_NAME:-default}
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www/frontend
      - frontend_dependencies:/var/www/frontend/node_modules
      - frontend_npm_cache:/home/node/.npm
    env_file:
      - ./frontend/.env
    networks:
      - default-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

volumes:
  frontend_dependencies:
  frontend_npm_cache:

networks:
  default-network:
    driver: bridge
